### PR TITLE
Removed Overview, added navigation to Homescreen, bottomNav color correction

### PR DESCRIPTION
**Pull request by Viccha18**
# Objective

Make some small changes prior to the merge of the bottom nav bar and the new homescreen
- removed overview.kt, overviewViewmodel.kt, route "OVERVIEW" & "EVENTS"
- added navigation to the bottomNav of Homescreen() in Home.kt
- corrected colors of the selected tab

### CODE REVIEW

**Review by Nath-Assa — APPROVED** [review]
LGTM!

**Review by jgeaso1266 — APPROVED** [review]
LGTM

**Review by jgeaso1266 — CHANGES_REQUESTED** [review]
LGTM, but it looks like one of the changes is breaking a test. Not sure if it's a problem with the test or with your code.

**Comment by Viccha18** [comment]
I'm currently trying to figure out why it does not pass the test

**Review by jgeaso1266 — APPROVED** [review]
LGTM

**Pull request merged**
