### PR TITLE
Add architecture diagram image and link to README.

### PR DESCRIPTION
**Pull request by jgeaso1266**
## Objective
Develop a comprehensive architecture diagram that clearly illustrates the system's structure. This diagram is not the final one, but provides a good start.

### CODE REVIEW

**Review by Viccha18 — APPROVED** [review]
Looks like a good base ! Thanks for the work !
I just have a remark : the arrows are a bit thick and make it a little hard to read and to see at first glance which blocks points to which. Maybe if the blocks are more spaced or rearranged it can look less crowded ?

**Review by Nath-Assa — APPROVED** [review]
Thanks for addressing the feedback! LGTM

**Review by achillet3 — APPROVED** [review]
The architecture looks good to me. All UI Layers have access to the necessary Data Layers.

**Review by achillet3 — APPROVED** [review]
Forgot to add the image to my review.

**Pull request merged**
